<a href="https://colab.research.google.com/github/luizrenault/tp547/blob/main/trabalho_2/questao_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy
!pip install matplotlib



In [58]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
import random

m=10000
n=np.random.multinomial(10, [0.25]*4, m) #geração de m amostras seguindo a lei multinomial

print(n)

P=sum((n[:, 0:2:1] == [2,2]).sum(1) == 2) / m #contando em quantas amostras ocorreu o resultado desejado

print("Frequência relativa simulada: %f" % P)


#Cálculo analítico multinomial
vec=np.array(range(0, 6))
p = sum(scipy.special.factorial(10) / (scipy.special.factorial(2) * scipy.special.factorial(2) * scipy.special.factorial(vec)  * scipy.special.factorial(6-vec)) * 0.25**10)
print("Probabilidade analítica: %f" % p)

######## Para o experimento sem reposição

vec = np.reshape([[1]*10, [2]*10, [3]*10, [4]*10],40)
#print(vec)

s=0

for i in range(m):
  n = np.array(random.sample(sorted(vec), 10)) #sem reposição
#  n = np.array(random.choices(sorted(vec), k=10)) #com reposição
  n = [sum(n==1), sum(n==2), sum(n==3), sum(n==4)]
  s+=sum(np.array(n[0:2])==[2,2])==2

print("Probabilidade para o experimento sem reposição é: %f" % (s/m))
print("Para o experimento sem reposição a probabilidade é maior.")



[[2 5 2 1]
 [0 3 5 2]
 [5 3 1 1]
 ...
 [3 2 1 4]
 [5 2 2 1]
 [3 3 2 2]]
Frequência relativa simulada: 0.075900
Probabilidade analítica: 0.075703
Probabilidade para o experimento sem reposição é: 0.091000
Para o experimento sem reposição a probabilidade é maior.
