<a href="https://colab.research.google.com/github/luizrenault/tp547/blob/main/trabalho_2/questao_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy
!pip install matplotlib



In [22]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
import random

def multinomial(k, P, m):
  A=np.random.uniform(0,1,k*m);
  acum = 0
  i=0
  n = range(1, 1 + np.size(P))
  A = np.reshape(A, (m,k))
  a = np.zeros_like(A)
  r=np.array([])

  for p in P:
    b=np.array(np.array(A>=acum) * np.array(A<(acum+p)))
    a+=b * n[i]

    c=b.sum(1)
    r=np.append(r, c)
    acum+=p
    i+=1
  r=np.transpose(np.reshape(r, (np.size(P),m)))
  #print(a)
  #print(r)
  return a

m=10000
n=multinomial(4, [1/6]*6, m) #geração de m amostras seguindo a lei multinomial


print(n)
n=np.sum(n,1)

prize = 9

v = (np.array(n< prize) * 9 + np.array(n>= prize) * -1)
v=sum(v)/m

print("O ganho médio é: %f" % v)



[[2. 5. 3. 5.]
 [1. 3. 3. 1.]
 [5. 5. 1. 6.]
 ...
 [2. 4. 4. 4.]
 [3. 2. 4. 4.]
 [5. 1. 5. 6.]]
O ganho médio é: -0.483000
