<a href="https://colab.research.google.com/github/luizrenault/tp547/blob/main/trabalho_2/questao_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy
!pip install matplotlib



In [124]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
import random

def sem_reposicao(k, P, m):
  A=np.random.uniform(0,1,k*m);
  acum = 0
  n = range(1, 1 + np.size(P))
  A = np.reshape(A, (m,k))
  ps = np.size(P)
  r=np.zeros((m,ps))
  a=np.zeros((m, k))

  for i in range(m):
    PP=np.array(P)
    for j in range(k):
      ii=1
      acum=0
      PPP = np.array(PP)/sum(PP)
      for ppp in PPP:
        if A[i,j]>=acum and A[i,j]<(acum+ppp) :
          a[i,j]=ii
          PP[ii-1]-=1
          r[i,ii-1]+=1
          break
        acum+=ppp
        ii+=1
  #print(a)
  #print(r)
  return r

def multinomial(k, P, m):
  A=np.random.uniform(0,1,k*m);
  acum = 0
  i=0
  n = range(1, 1 + np.size(P))
  A = np.reshape(A, (m,k))
  a = np.zeros_like(A)
  r=np.array([])

  for p in P:
    b=np.array(np.array(A>=acum) * np.array(A<(acum+p)))
    a+=b * n[i]

    c=b.sum(1)
    r=np.append(r, c)
    acum+=p
    i+=1
  r=np.transpose(np.reshape(r, (np.size(P),m)))
  #print(a)
  #print(r)
  return r


m=10000
n=multinomial(10, [0.25]*4, m) #geração de m amostras seguindo a lei multinomial

print(n)

P=sum((n[:, 0:2:1] == [2,2]).sum(1) == 2) / m #contando em quantas amostras ocorreu o resultado desejado

print("Frequência relativa simulada: %f" % P)


#Cálculo analítico multinomial
vec=np.array(range(0, 6))
p = sum(scipy.special.factorial(10) / (scipy.special.factorial(2) * scipy.special.factorial(2) * scipy.special.factorial(vec)  * scipy.special.factorial(6-vec)) * 0.25**10)
print("Probabilidade analítica: %f" % p)

######## Para o experimento sem reposição

vec = np.reshape([[1]*10, [2]*10, [3]*10, [4]*10],40)
#print(vec)

s=0

n=sem_reposicao(10, [10]*4, m)
print(n)
P=sum((n[:, 0:2:1] == [2,2]).sum(1) == 2) / m #contando em quantas amostras ocorreu o resultado desejado

print("Probabilidade para o experimento sem reposição é: %f" % (P))
print("Para o experimento sem reposição a probabilidade é maior.")

[[2. 4. 0. 4.]
 [3. 1. 3. 3.]
 [6. 1. 2. 1.]
 ...
 [4. 1. 1. 4.]
 [2. 2. 3. 3.]
 [2. 2. 2. 4.]]
Frequência relativa simulada: 0.075100
Probabilidade analítica: 0.075703
[[2. 2. 5. 1.]
 [1. 4. 1. 4.]
 [0. 3. 3. 4.]
 ...
 [3. 2. 1. 4.]
 [3. 1. 3. 3.]
 [3. 1. 1. 5.]]
Probabilidade para o experimento sem reposição é: 0.097400
Para o experimento sem reposição a probabilidade é maior.
