<a href="https://colab.research.google.com/github/luizrenault/tp547/blob/main/trabalho_2/questao_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
!pip install numpy
!pip install matplotlib



In [75]:
import numpy as np
import matplotlib.pyplot as plt
import scipy


m=10000
n=np.random.multinomial(10, [0.25]*4, m) #geração de m amostras seguindo a lei multinomial

print(n)

P=sum((n[:, 0:2:1] == [2,2]).sum(1) == 2) / m #contando em quantas amostras ocorreu o resultado desejado

print("Frequência relativa simulada: %f" % P)


#Cálculo analítico multinomial
vec=np.array(range(0, 6))
p = sum(scipy.special.factorial(10) / (scipy.special.factorial(2) * scipy.special.factorial(2) * scipy.special.factorial(vec)  * scipy.special.factorial(6-vec)) * 0.25**10)
print("Probabilidade analítica: %f" % p)




[[5 2 1 2]
 [2 3 0 5]
 [3 1 5 1]
 ...
 [4 1 2 3]
 [2 4 3 1]
 [6 0 2 2]]
Frequência relativa simulada: 0.075700
Probabilidade analítica: 0.075703
